[package]
name = "sink-dynamic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = { workspace = true }
eyre = "0.6.8"
rand = "0.8.5"
uhlc = "0.5.1"
bytemuck = "1.12"
csv = "1.1.6"
chrono = "0.4.38"

[package.metadata.arceos]
features = ["net", "multitask", "fs", "irq", "sched_rr"]