[package]
name = "std-tokio-echo"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29", features = ["macros", "rt", "io-util", "net"] }

[package.metadata.arceos]
features = ["net", "multitask"]
