[package]
name = "arceos-shell"
version = "0.1.0"
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
use-ramfs = ["axstd/myfs", "dep:axfs_vfs", "dep:axfs_ramfs", "dep:crate_interface"]
default = []

[dependencies]
axfs_vfs = { git = "https://github.com/arceos-org/axfs_crates.git", rev = "155130301c91df11a9529a06e236bb915aa2bf1c", optional = true }
axfs_ramfs = { git = "https://github.com/arceos-org/axfs_crates.git", rev = "155130301c91df11a9529a06e236bb915aa2bf1c", optional = true }
crate_interface = { version = "0.1", optional = true }
axstd = { workspace = true, features = ["alloc", "fs"], optional = true }
